#!/usr/bin/env bash
set -euo pipefail

# Updates an existing BackUpLife installation created by install_debian13.sh.
# Run this from a freshly pulled repo checkout:
#   git pull --ff-only
#   sudo bash update_debian13.sh

APP_DIR="/opt/backuplife"
SERVICE_FILE="/etc/systemd/system/backuplife.service"
NGINX_FILE="/etc/nginx/sites-available/backuplife"
DOMAIN="${1:-_}"
APP_USER="backuplife"
ENV_FILE="$APP_DIR/.env"
BUILD_SHA="$(git rev-parse --short HEAD 2>/dev/null || true)"
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

apt-get update
apt-get install -y python3 python3-venv python3-pip nginx sqlite3 rsync openssl iproute2

if [ ! -d "$APP_DIR" ]; then
  echo "BackUpLife ist noch nicht installiert: $APP_DIR fehlt."
  echo "Bitte zuerst: sudo bash install_debian13.sh"
  exit 1
fi

# Deploy application code but never overwrite runtime data.
rsync -a --delete \
  --exclude ".git/" \
  --exclude ".venv/" \
  --exclude ".env" \
  --exclude "instance/" \
  --exclude "__pycache__/" \
  --exclude ".pytest_cache/" \
  ./ "$APP_DIR"/

cd "$APP_DIR"
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt

mkdir -p instance/uploads
chown -R "$APP_USER":"$APP_USER" "$APP_DIR"

if [ ! -f "$ENV_FILE" ]; then
  FLASK_SECRET_KEY="$(openssl rand -hex 32)"
  BACKUPLIFE_APP_KEY="$(openssl rand -hex 32)"
  cat > "$ENV_FILE" <<EOF
# Generated by update_debian13.sh (missing previously)
FLASK_SECRET_KEY=$FLASK_SECRET_KEY
BACKUPLIFE_APP_KEY=$BACKUPLIFE_APP_KEY
BACKUPLIFE_DB_PATH=$APP_DIR/instance/backuplife.db
BACKUPLIFE_UPLOAD_DIR=$APP_DIR/instance/uploads
HOST=127.0.0.1
PORT=8000
BACKUPLIFE_TRUST_PROXY=1
# BACKUPLIFE_COOKIE_SECURE=1
EOF
  chown "$APP_USER":"$APP_USER" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
else
  if grep -qE 'FLASK_SECRET_KEY=change-me|AETERNA_APP_KEY=change-me-too|BACKUPLIFE_APP_KEY=change-me-too' "$ENV_FILE"; then
    FLASK_SECRET_KEY="$(openssl rand -hex 32)"
    BACKUPLIFE_APP_KEY="$(openssl rand -hex 32)"
    cat > "$ENV_FILE" <<EOF
# Re-generated by update_debian13.sh (placeholder keys detected)
FLASK_SECRET_KEY=$FLASK_SECRET_KEY
BACKUPLIFE_APP_KEY=$BACKUPLIFE_APP_KEY
BACKUPLIFE_DB_PATH=$APP_DIR/instance/backuplife.db
BACKUPLIFE_UPLOAD_DIR=$APP_DIR/instance/uploads
HOST=127.0.0.1
PORT=8000
BACKUPLIFE_TRUST_PROXY=1
# BACKUPLIFE_COOKIE_SECURE=1
EOF
    chown "$APP_USER":"$APP_USER" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
  fi
fi

# Always refresh build info on update runs.
if [ -n "${BUILD_SHA:-}" ]; then
  if grep -q '^BACKUPLIFE_BUILD_SHA=' "$ENV_FILE"; then
    sed -i "s/^BACKUPLIFE_BUILD_SHA=.*/BACKUPLIFE_BUILD_SHA=$BUILD_SHA/" "$ENV_FILE"
  else
    echo "BACKUPLIFE_BUILD_SHA=$BUILD_SHA" >> "$ENV_FILE"
  fi
  if grep -q '^BACKUPLIFE_BUILD_DATE=' "$ENV_FILE"; then
    sed -i "s/^BACKUPLIFE_BUILD_DATE=.*/BACKUPLIFE_BUILD_DATE=$BUILD_DATE/" "$ENV_FILE"
  else
    echo "BACKUPLIFE_BUILD_DATE=$BUILD_DATE" >> "$ENV_FILE"
  fi
fi

# (Re)write Nginx config so domain changes apply.
cat > "$NGINX_FILE" <<EOF
server {
    listen 80;
    server_name $DOMAIN;

    client_max_body_size 25M;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

ln -sf "$NGINX_FILE" /etc/nginx/sites-enabled/backuplife
rm -f /etc/nginx/sites-enabled/default

systemctl daemon-reload
systemctl restart backuplife
nginx -t
systemctl restart nginx

echo "BackUpLife wurde aktualisiert."
echo "Service: systemctl status backuplife"
echo
PRIMARY_IP="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}')"
if [ -z "${PRIMARY_IP:-}" ]; then
  PRIMARY_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
fi
if [ -n "${PRIMARY_IP:-}" ]; then
  echo "Aufruf: http://$PRIMARY_IP/"
fi
if [ "${DOMAIN:-_}" != "_" ]; then
  echo "Aufruf (Domain): http://$DOMAIN/"
fi
echo
echo "Status:"
systemctl --no-pager --full status backuplife || true
echo
echo "Letzte Logs:"
journalctl -u backuplife -n 30 --no-pager || true
echo
echo "Port 8000 Listener:"
if command -v ss >/dev/null 2>&1; then
  ss -ltnp | grep -E '(:|\\.)8000($|[^0-9])' || echo "Kein Listener auf Port 8000 gefunden."
elif command -v lsof >/dev/null 2>&1; then
  lsof -nP -iTCP:8000 -sTCP:LISTEN || echo "Kein Listener auf Port 8000 gefunden."
elif command -v netstat >/dev/null 2>&1; then
  netstat -ltnp 2>/dev/null | grep -E '(:|\\.)8000($|[^0-9])' || echo "Kein Listener auf Port 8000 gefunden."
else
  echo "Port-Check nicht möglich (ss/lsof/netstat fehlt)."
fi
echo
echo "Hinweis: Wenn du per CLI starten willst, stoppe vorher den Service oder nutze einen anderen Port:"
echo "  systemctl stop backuplife"
echo "  PORT=8001 python3 app.py"
