#!/usr/bin/env bash
set -euo pipefail

# Updates an existing BackUpLife installation created by install_debian13.sh.
# Run this from a freshly pulled repo checkout:
#   git pull --ff-only
#   sudo bash update_debian13.sh

APP_DIR="/opt/backuplife"
SERVICE_FILE="/etc/systemd/system/backuplife.service"
NGINX_FILE="/etc/nginx/sites-available/backuplife"
DOMAIN="${1:-_}"
APP_USER="backuplife"
ENV_FILE="$APP_DIR/.env"

apt-get update
apt-get install -y python3 python3-venv python3-pip nginx sqlite3 rsync openssl

if [ ! -d "$APP_DIR" ]; then
  echo "BackUpLife ist noch nicht installiert: $APP_DIR fehlt."
  echo "Bitte zuerst: sudo bash install_debian13.sh"
  exit 1
fi

# Deploy application code but never overwrite runtime data.
rsync -a --delete \
  --exclude ".git/" \
  --exclude ".venv/" \
  --exclude ".env" \
  --exclude "instance/" \
  --exclude "__pycache__/" \
  --exclude ".pytest_cache/" \
  ./ "$APP_DIR"/

cd "$APP_DIR"
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt

mkdir -p instance/uploads
chown -R "$APP_USER":"$APP_USER" "$APP_DIR"

if [ ! -f "$ENV_FILE" ]; then
  FLASK_SECRET_KEY="$(openssl rand -hex 32)"
  BACKUPLIFE_APP_KEY="$(openssl rand -hex 32)"
  cat > "$ENV_FILE" <<EOF
# Generated by update_debian13.sh (missing previously)
FLASK_SECRET_KEY=$FLASK_SECRET_KEY
BACKUPLIFE_APP_KEY=$BACKUPLIFE_APP_KEY
BACKUPLIFE_DB_PATH=$APP_DIR/instance/backuplife.db
BACKUPLIFE_UPLOAD_DIR=$APP_DIR/instance/uploads
HOST=127.0.0.1
PORT=8000
BACKUPLIFE_TRUST_PROXY=1
# BACKUPLIFE_COOKIE_SECURE=1
EOF
  chown "$APP_USER":"$APP_USER" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
else
  if grep -qE 'FLASK_SECRET_KEY=change-me|AETERNA_APP_KEY=change-me-too|BACKUPLIFE_APP_KEY=change-me-too' "$ENV_FILE"; then
    FLASK_SECRET_KEY="$(openssl rand -hex 32)"
    BACKUPLIFE_APP_KEY="$(openssl rand -hex 32)"
    cat > "$ENV_FILE" <<EOF
# Re-generated by update_debian13.sh (placeholder keys detected)
FLASK_SECRET_KEY=$FLASK_SECRET_KEY
BACKUPLIFE_APP_KEY=$BACKUPLIFE_APP_KEY
BACKUPLIFE_DB_PATH=$APP_DIR/instance/backuplife.db
BACKUPLIFE_UPLOAD_DIR=$APP_DIR/instance/uploads
HOST=127.0.0.1
PORT=8000
BACKUPLIFE_TRUST_PROXY=1
# BACKUPLIFE_COOKIE_SECURE=1
EOF
    chown "$APP_USER":"$APP_USER" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
  fi
fi

# (Re)write Nginx config so domain changes apply.
cat > "$NGINX_FILE" <<EOF
server {
    listen 80;
    server_name $DOMAIN;

    client_max_body_size 25M;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

ln -sf "$NGINX_FILE" /etc/nginx/sites-enabled/backuplife
rm -f /etc/nginx/sites-enabled/default

systemctl daemon-reload
systemctl restart backuplife
nginx -t
systemctl restart nginx

echo "BackUpLife wurde aktualisiert."
echo "Service: systemctl status backuplife"
