#!/usr/bin/env bash
set -euo pipefail

# Generates a secure .env for CLI usage.
# It will NOT overwrite an existing .env unless --force is provided.

FORCE=0
if [[ "${1:-}" == "--force" ]]; then
  FORCE=1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

if [[ -f "$ENV_FILE" && "$FORCE" -ne 1 ]]; then
  echo ".env exists at $ENV_FILE (use --force to overwrite)."
  exit 0
fi

if command -v openssl >/dev/null 2>&1; then
  FLASK_SECRET_KEY="$(openssl rand -hex 32)"
  BACKUPLIFE_APP_KEY="$(openssl rand -hex 32)"
else
  # Fallback: still decent randomness, but prefer openssl.
  FLASK_SECRET_KEY="$(python3 - <<'PY'\nimport secrets\nprint(secrets.token_hex(32))\nPY)"
  BACKUPLIFE_APP_KEY="$(python3 - <<'PY'\nimport secrets\nprint(secrets.token_hex(32))\nPY)"
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/init_env.sh
FLASK_SECRET_KEY=$FLASK_SECRET_KEY
BACKUPLIFE_APP_KEY=$BACKUPLIFE_APP_KEY
BACKUPLIFE_DB_PATH=$ROOT_DIR/instance/backuplife.db
BACKUPLIFE_UPLOAD_DIR=$ROOT_DIR/instance/uploads
HOST=127.0.0.1
PORT=8000
BACKUPLIFE_TRUST_PROXY=1
# BACKUPLIFE_COOKIE_SECURE=1
EOF

mkdir -p "$ROOT_DIR/instance/uploads"
chmod 600 "$ENV_FILE" || true

echo "Wrote secure .env to $ENV_FILE"
echo "Next:"
echo "  python3 app.py"

